package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*AddVMMethodNotAllowed Invalid input

swagger:response addVmMethodNotAllowed
*/
type AddVMMethodNotAllowed struct {
}

// NewAddVMMethodNotAllowed creates AddVMMethodNotAllowed with default headers values
func NewAddVMMethodNotAllowed() *AddVMMethodNotAllowed {
	return &AddVMMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddVMMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
