package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jianqiu/vps/models"
)

/*AddVMOK add a new vm into the pool

swagger:response addVmOK
*/
type AddVMOK struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewAddVMOK creates AddVMOK with default headers values
func NewAddVMOK() *AddVMOK {
	return &AddVMOK{}
}

// WithPayload adds the payload to the add Vm o k response
func (o *AddVMOK) WithPayload(payload string) *AddVMOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add Vm o k response
func (o *AddVMOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddVMOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*AddVMDefault unexpected error

swagger:response addVmDefault
*/
type AddVMDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddVMDefault creates AddVMDefault with default headers values
func NewAddVMDefault(code int) *AddVMDefault {
	if code <= 0 {
		code = 500
	}

	return &AddVMDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add Vm default response
func (o *AddVMDefault) WithStatusCode(code int) *AddVMDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add Vm default response
func (o *AddVMDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add Vm default response
func (o *AddVMDefault) WithPayload(payload *models.Error) *AddVMDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add Vm default response
func (o *AddVMDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddVMDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
