package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DeleteVMBadRequest Invalid vm value

swagger:response deleteVmBadRequest
*/
type DeleteVMBadRequest struct {
}

// NewDeleteVMBadRequest creates DeleteVMBadRequest with default headers values
func NewDeleteVMBadRequest() *DeleteVMBadRequest {
	return &DeleteVMBadRequest{}
}

// WriteResponse to the client
func (o *DeleteVMBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
