package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jianqiu/vps/models"
)

/*FindVmsByDeploymentOK successful operation

swagger:response findVmsByDeploymentOK
*/
type FindVmsByDeploymentOK struct {

	// In: body
	Payload *models.VmsResponse `json:"body,omitempty"`
}

// NewFindVmsByDeploymentOK creates FindVmsByDeploymentOK with default headers values
func NewFindVmsByDeploymentOK() *FindVmsByDeploymentOK {
	return &FindVmsByDeploymentOK{}
}

// WithPayload adds the payload to the find vms by deployment o k response
func (o *FindVmsByDeploymentOK) WithPayload(payload *models.VmsResponse) *FindVmsByDeploymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find vms by deployment o k response
func (o *FindVmsByDeploymentOK) SetPayload(payload *models.VmsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindVmsByDeploymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindVmsByDeploymentBadRequest Invalid deployment name value

swagger:response findVmsByDeploymentBadRequest
*/
type FindVmsByDeploymentBadRequest struct {
}

// NewFindVmsByDeploymentBadRequest creates FindVmsByDeploymentBadRequest with default headers values
func NewFindVmsByDeploymentBadRequest() *FindVmsByDeploymentBadRequest {
	return &FindVmsByDeploymentBadRequest{}
}

// WriteResponse to the client
func (o *FindVmsByDeploymentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
