package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindVmsByDeploymentHandlerFunc turns a function with the right signature into a find vms by deployment handler
type FindVmsByDeploymentHandlerFunc func(FindVmsByDeploymentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FindVmsByDeploymentHandlerFunc) Handle(params FindVmsByDeploymentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FindVmsByDeploymentHandler interface for that can handle valid find vms by deployment params
type FindVmsByDeploymentHandler interface {
	Handle(FindVmsByDeploymentParams, interface{}) middleware.Responder
}

// NewFindVmsByDeployment creates a new http.Handler for the find vms by deployment operation
func NewFindVmsByDeployment(ctx *middleware.Context, handler FindVmsByDeploymentHandler) *FindVmsByDeployment {
	return &FindVmsByDeployment{Context: ctx, Handler: handler}
}

/*FindVmsByDeployment swagger:route GET /vms/findByDeployment vm findVmsByDeployment

Finds Vms by deployment name

Multiple deployment values can be provided with comma seperated strings

*/
type FindVmsByDeployment struct {
	Context *middleware.Context
	Handler FindVmsByDeploymentHandler
}

func (o *FindVmsByDeployment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewFindVmsByDeploymentParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
