package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jianqiu/vps/models"
)

/*FindVmsByDeploymentOK successful operation

swagger:response findVmsByDeploymentOK
*/
type FindVmsByDeploymentOK struct {

	// In: body
	Payload *models.VmsResponse `json:"body,omitempty"`
}

// NewFindVmsByDeploymentOK creates FindVmsByDeploymentOK with default headers values
func NewFindVmsByDeploymentOK() *FindVmsByDeploymentOK {
	return &FindVmsByDeploymentOK{}
}

// WithPayload adds the payload to the find vms by deployment o k response
func (o *FindVmsByDeploymentOK) WithPayload(payload *models.VmsResponse) *FindVmsByDeploymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find vms by deployment o k response
func (o *FindVmsByDeploymentOK) SetPayload(payload *models.VmsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindVmsByDeploymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindVmsByDeploymentNotFound vm not found

swagger:response findVmsByDeploymentNotFound
*/
type FindVmsByDeploymentNotFound struct {
}

// NewFindVmsByDeploymentNotFound creates FindVmsByDeploymentNotFound with default headers values
func NewFindVmsByDeploymentNotFound() *FindVmsByDeploymentNotFound {
	return &FindVmsByDeploymentNotFound{}
}

// WriteResponse to the client
func (o *FindVmsByDeploymentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*FindVmsByDeploymentDefault unexpected error

swagger:response findVmsByDeploymentDefault
*/
type FindVmsByDeploymentDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindVmsByDeploymentDefault creates FindVmsByDeploymentDefault with default headers values
func NewFindVmsByDeploymentDefault(code int) *FindVmsByDeploymentDefault {
	if code <= 0 {
		code = 500
	}

	return &FindVmsByDeploymentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find vms by deployment default response
func (o *FindVmsByDeploymentDefault) WithStatusCode(code int) *FindVmsByDeploymentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find vms by deployment default response
func (o *FindVmsByDeploymentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find vms by deployment default response
func (o *FindVmsByDeploymentDefault) WithPayload(payload *models.Error) *FindVmsByDeploymentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find vms by deployment default response
func (o *FindVmsByDeploymentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindVmsByDeploymentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
