package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jianqiu/vps/models"
)

/*FindVmsByStatesOK successful operation

swagger:response findVmsByStatesOK
*/
type FindVmsByStatesOK struct {

	// In: body
	Payload *models.VmsResponse `json:"body,omitempty"`
}

// NewFindVmsByStatesOK creates FindVmsByStatesOK with default headers values
func NewFindVmsByStatesOK() *FindVmsByStatesOK {
	return &FindVmsByStatesOK{}
}

// WithPayload adds the payload to the find vms by states o k response
func (o *FindVmsByStatesOK) WithPayload(payload *models.VmsResponse) *FindVmsByStatesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find vms by states o k response
func (o *FindVmsByStatesOK) SetPayload(payload *models.VmsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindVmsByStatesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindVmsByStatesBadRequest Invalid state value

swagger:response findVmsByStatesBadRequest
*/
type FindVmsByStatesBadRequest struct {
}

// NewFindVmsByStatesBadRequest creates FindVmsByStatesBadRequest with default headers values
func NewFindVmsByStatesBadRequest() *FindVmsByStatesBadRequest {
	return &FindVmsByStatesBadRequest{}
}

// WriteResponse to the client
func (o *FindVmsByStatesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
