package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jianqiu/vps/models"
)

/*GetVMByCidOK successful operation

swagger:response getVmByCidOK
*/
type GetVMByCidOK struct {

	// In: body
	Payload *models.VMResponse `json:"body,omitempty"`
}

// NewGetVMByCidOK creates GetVMByCidOK with default headers values
func NewGetVMByCidOK() *GetVMByCidOK {
	return &GetVMByCidOK{}
}

// WithPayload adds the payload to the get Vm by cid o k response
func (o *GetVMByCidOK) WithPayload(payload *models.VMResponse) *GetVMByCidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Vm by cid o k response
func (o *GetVMByCidOK) SetPayload(payload *models.VMResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVMByCidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetVMByCidBadRequest Invalid ID supplied

swagger:response getVmByCidBadRequest
*/
type GetVMByCidBadRequest struct {
}

// NewGetVMByCidBadRequest creates GetVMByCidBadRequest with default headers values
func NewGetVMByCidBadRequest() *GetVMByCidBadRequest {
	return &GetVMByCidBadRequest{}
}

// WriteResponse to the client
func (o *GetVMByCidBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*GetVMByCidNotFound Vm not found

swagger:response getVmByCidNotFound
*/
type GetVMByCidNotFound struct {
}

// NewGetVMByCidNotFound creates GetVMByCidNotFound with default headers values
func NewGetVMByCidNotFound() *GetVMByCidNotFound {
	return &GetVMByCidNotFound{}
}

// WriteResponse to the client
func (o *GetVMByCidNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
