package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jianqiu/vps/models"
)

/*ListVMOK successful operation

swagger:response listVmOK
*/
type ListVMOK struct {

	// In: body
	Payload *models.VmsResponse `json:"body,omitempty"`
}

// NewListVMOK creates ListVMOK with default headers values
func NewListVMOK() *ListVMOK {
	return &ListVMOK{}
}

// WithPayload adds the payload to the list Vm o k response
func (o *ListVMOK) WithPayload(payload *models.VmsResponse) *ListVMOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list Vm o k response
func (o *ListVMOK) SetPayload(payload *models.VmsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVMOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListVMMethodNotAllowed Invalid input

swagger:response listVmMethodNotAllowed
*/
type ListVMMethodNotAllowed struct {
}

// NewListVMMethodNotAllowed creates ListVMMethodNotAllowed with default headers values
func NewListVMMethodNotAllowed() *ListVMMethodNotAllowed {
	return &ListVMMethodNotAllowed{}
}

// WriteResponse to the client
func (o *ListVMMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
