package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	"github.com/jianqiu/vps/models"
)

// OrderVMByFilterHandlerFunc turns a function with the right signature into a order Vm by filter handler
type OrderVMByFilterHandlerFunc func(OrderVMByFilterParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn OrderVMByFilterHandlerFunc) Handle(params OrderVMByFilterParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// OrderVMByFilterHandler interface for that can handle valid order Vm by filter params
type OrderVMByFilterHandler interface {
	Handle(OrderVMByFilterParams, *models.User) middleware.Responder
}

// NewOrderVMByFilter creates a new http.Handler for the order Vm by filter operation
func NewOrderVMByFilter(ctx *middleware.Context, handler OrderVMByFilterHandler) *OrderVMByFilter {
	return &OrderVMByFilter{Context: ctx, Handler: handler}
}

/*OrderVMByFilter swagger:route POST /vms/order vm orderVmByFilter

Order a free vm by filters (cpu, memory, private_vlan, public_vlan, state)

*/
type OrderVMByFilter struct {
	Context *middleware.Context
	Handler OrderVMByFilterHandler
}

func (o *OrderVMByFilter) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewOrderVMByFilterParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
