package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateVMWithStateHandlerFunc turns a function with the right signature into a update Vm with state handler
type UpdateVMWithStateHandlerFunc func(UpdateVMWithStateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateVMWithStateHandlerFunc) Handle(params UpdateVMWithStateParams) middleware.Responder {
	return fn(params)
}

// UpdateVMWithStateHandler interface for that can handle valid update Vm with state params
type UpdateVMWithStateHandler interface {
	Handle(UpdateVMWithStateParams) middleware.Responder
}

// NewUpdateVMWithState creates a new http.Handler for the update Vm with state operation
func NewUpdateVMWithState(ctx *middleware.Context, handler UpdateVMWithStateHandler) *UpdateVMWithState {
	return &UpdateVMWithState{Context: ctx, Handler: handler}
}

/*UpdateVMWithState swagger:route PUT /vms/{cid} vm updateVmWithState

Updates a vm in the pool with state

*/
type UpdateVMWithState struct {
	Context *middleware.Context
	Handler UpdateVMWithStateHandler
}

func (o *UpdateVMWithState) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateVMWithStateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
