package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*UpdateVMWithStateMethodNotAllowed Invalid input

swagger:response updateVmWithStateMethodNotAllowed
*/
type UpdateVMWithStateMethodNotAllowed struct {
}

// NewUpdateVMWithStateMethodNotAllowed creates UpdateVMWithStateMethodNotAllowed with default headers values
func NewUpdateVMWithStateMethodNotAllowed() *UpdateVMWithStateMethodNotAllowed {
	return &UpdateVMWithStateMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateVMWithStateMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
