package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jianqiu/vps/models"
)

// NewUpdateVMWithStateParams creates a new UpdateVMWithStateParams object
// with the default values initialized.
func NewUpdateVMWithStateParams() UpdateVMWithStateParams {
	var ()
	return UpdateVMWithStateParams{}
}

// UpdateVMWithStateParams contains all the bound params for the update Vm with state operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateVmWithState
type UpdateVMWithStateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Vm state that needs to be updated
	  In: body
	*/
	Body *models.VMState
	/*ID of vm that needs to be updated
	  Required: true
	  In: path
	*/
	Cid int32
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateVMWithStateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.VMState
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	}

	rCid, rhkCid, _ := route.Params.GetOK("cid")
	if err := o.bindCid(rCid, rhkCid, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateVMWithStateParams) bindCid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("cid", "path", "int32", raw)
	}
	o.Cid = value

	return nil
}
