package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	"github.com/jianqiu/vps/models"
)

// UpdateVMHandlerFunc turns a function with the right signature into a update Vm handler
type UpdateVMHandlerFunc func(UpdateVMParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateVMHandlerFunc) Handle(params UpdateVMParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UpdateVMHandler interface for that can handle valid update Vm params
type UpdateVMHandler interface {
	Handle(UpdateVMParams, *models.User) middleware.Responder
}

// NewUpdateVM creates a new http.Handler for the update Vm operation
func NewUpdateVM(ctx *middleware.Context, handler UpdateVMHandler) *UpdateVM {
	return &UpdateVM{Context: ctx, Handler: handler}
}

/*UpdateVM swagger:route PUT /vms vm updateVm

Update an existing vm

*/
type UpdateVM struct {
	Context *middleware.Context
	Handler UpdateVMHandler
}

func (o *UpdateVM) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateVMParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
