package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/jianqiu/vps/models"
)

// NewUpdateVMParams creates a new UpdateVMParams object
// with the default values initialized.
func NewUpdateVMParams() UpdateVMParams {
	var ()
	return UpdateVMParams{}
}

// UpdateVMParams contains all the bound params for the update Vm operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateVm
type UpdateVMParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Vm object that needs to be added to the pool
	  In: body
	*/
	Body *models.VM
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateVMParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.VM
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
