package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*UpdateVMBadRequest Invalid ID supplied

swagger:response updateVmBadRequest
*/
type UpdateVMBadRequest struct {
}

// NewUpdateVMBadRequest creates UpdateVMBadRequest with default headers values
func NewUpdateVMBadRequest() *UpdateVMBadRequest {
	return &UpdateVMBadRequest{}
}

// WriteResponse to the client
func (o *UpdateVMBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*UpdateVMNotFound Vm not found

swagger:response updateVmNotFound
*/
type UpdateVMNotFound struct {
}

// NewUpdateVMNotFound creates UpdateVMNotFound with default headers values
func NewUpdateVMNotFound() *UpdateVMNotFound {
	return &UpdateVMNotFound{}
}

// WriteResponse to the client
func (o *UpdateVMNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*UpdateVMMethodNotAllowed Validation exception

swagger:response updateVmMethodNotAllowed
*/
type UpdateVMMethodNotAllowed struct {
}

// NewUpdateVMMethodNotAllowed creates UpdateVMMethodNotAllowed with default headers values
func NewUpdateVMMethodNotAllowed() *UpdateVMMethodNotAllowed {
	return &UpdateVMMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateVMMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
