package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Error error
// swagger:model Error
type Error struct {

	// etype
	Etype ErrorType `json:"etype,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this error
func (m *Error) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEtype(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Error) validateEtype(formats strfmt.Registry) error {

	if swag.IsZero(m.Etype) { // not required
		return nil
	}

	if err := m.Etype.Validate(formats); err != nil {
		return err
	}

	return nil
}
