package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// VMResponse Vm response
// swagger:model VmResponse
type VMResponse struct {

	// error
	Error *Error `json:"error,omitempty"`

	// vm
	VM *VM `json:"vm,omitempty"`
}

// Validate validates this Vm response
func (m *VMResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateVM(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VMResponse) validateError(formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {

		if err := m.Error.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}

func (m *VMResponse) validateVM(formats strfmt.Registry) error {

	if swag.IsZero(m.VM) { // not required
		return nil
	}

	if m.VM != nil {

		if err := m.VM.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
